name = "tapl-read-lean"
version = "0.1.0"
defaultTargets = ["tapl-read-lean"]

[[lean_lib]]
name = "TaplReadLean"

[[lean_lib]]
name = "TaPL2"
globs = ["TaPL2.+"]

[[require]]
name = "mathlib"
scope = "leanprover-community"